- name: this playbook is to install catalogue component
  hosts: catalogue
  become: yes

  tasks:
    - name: stupping nodejs repo
      ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash
    
    - name: installing nodejs
      ansible.builtin.yum:
        name: nodejs
        state: installed
    
    - name: checking if roboshop user is present or not
      ansible.builtin.command: id roboshop
      register: output
      ignore_errors: true
    
    - name: printing the output of user is present or not
      ansible.builtin.debug:
        msg: "{{output}}"

    - name: printing the output of user is presnt or not
      ansible.builtin.debug:
        msg: "{{output.rc}}"    

