- name: gthis playbook is to configure payment service
  hosts: payment
  become: yes

  tasks:
    - name: install Python 3.6
      ansible.builtin.yum:
          name: "{{item}}"
          state: installed
      loop: 
        - python36
        - gcc
        - python3-devel
    
    - name: checking if roboshop user is present or not
      ansible.builtin.command: id roboshop
      register: output
      ignore_errors: true
    
    - name: printing the output of user is present or not
      ansible.builtin.debug:
        msg: "{{output}}"

    - name: printing the output of user is presnt or not
      ansible.builtin.debug:
        msg: "{{output.rc}}"    
    
    - name: creating roboshop user
      ansible.builtin.user: 
        name: roboshop
      when: output.rc != 0

    - name: checking /app directory exists or not
      ansible.builtin.stat:
        path: /app
      register: directory
    
    - name: print the output of user directory present or not
      ansible.builtin.debug:
        msg: "{{directory}}"
    
    - name: create /app directory
      ansible.builtin.file:
        path: /app
        state: directory
      when: directory.stat.exists == false


    - name: download payment code in /tmp directory
      ansible.builtin.get_url:
        url: https://roboshop-builds.s3.amazonaws.com/payment.zip
        dest: /tmp

    - name: extract the payment.zip 
      ansible.builtin.unarchive:
        src: /tmp/payment
        dest: /app
        remote_src: yes

    - name: install application dependencies
      ansible.builtin.command: pip3.6 install -r requirements.txt
      args:
       chdir: /app

    - name: Setup SystemD payment Service
      ansible.builtin.copy:
        src: payment.service
        dest: /etc/systemd/system/

    - name: reloading the daemon service
      ansible.builtin.systemd:
        daemon_reload: true

    - name: starting and enbaling payment service
      ansible.builtin.servicve:
        name: payment
        state: restarted
        enabled: yes

        