- name: gthis playbook is to configure payment service
  hosts: payment
  become: yes

  tasks:
    - name: install Python 3.6
      ansible.builtin.yum:
          name: "{{items}}"
          state: installed
          loops: 
            - python36
            - gcc
            - python3-devel