- name: this playbbok is to install rabbitmq
  hosts: rabbitmq
  become: yes

  tasks:
    - name: Configure YUM Repos from the script provided by vendor.
      ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | bash
    
    - name: Configure YUM Repos for RabbitMQ.
      ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | bash

    - name: installing rabbitmq
      ansible.builtin.yum:
       name: rabbitmq-server
       state: installed

    - name: start and enable rabbitmq server
      ansible.builtin.servive:
        name: rabbitmq-server
        state: started
      enabled: yes

    - name: create roboshop user
      ansible.builtin.shell: rabbitmqctl add_user roboshop roboshop123

    - name : grant permissions to roboshop user
      ansible.builtin.shell: rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*"