- name: this playbook is for installing redis
  hosts: redis
  become: yes
  
  tasks:
    - name: installing redis
      ansible.builtin.yum:
        name: redis
        state: installed
    
    - name: edit the /redis.conf file to Update listen address from 127.0.0.1 to 0.0.0.0 
      ansible.builtin.replace:
        path: /etc/redis.conf
        regexp: '127.0.0.1'
        replace: '0.0.0.0'

    - name: starting and enabling redis 
      ansible.builtin.service:
        name: redis
        state: started
        enabled: yes
