- name: this pplaybook is for installing user component
  hosts: user
  become: yes

  tasks:
    - name: setuping nodejs repo
      ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

    - name: installing nodejs
      ansible.builtin.yum: 
        name: nodejs
        state: installed
    
    - name: check if roboshop user is present or not
      ansible.builtin.command: id roboshop
      register: out
      ignore_errors: true

    - name: print the output of roboshop user present or not
      ansible.builtin.debug:
        msg: "{{out}}"
    
    - name: print the exist status of roboshop user
      ansible.builtin.debug:
        msg: "{{out.rc}}"

    - name: creating the roboshop user
      ansible.builtin.user:
        name: roboshop
      when: out.rc != 0
    
    - name: check if /app directory is present or not
      ansible.builtin.stat:
        path: /app
      register: directory

    - name: print the output of /app directory
      ansible.builtin.debug:
        msg: "{{directory}}"
    
    - name: print the output exists of /app directory exists or not
      ansible.builtin.debug:
        msg: "{{directory.stat.exists}}"
    
    - name: creating /app directory
      ansible.builtin.file:
        path: /app
        state: directory
      when: directory.stat.exists == false

    - name: download application url
      ansible.builtin.get_url:
        url: https://roboshop-builds.s3.amazonaws.com/user.zip
        dest: /tmp
      
    - name: extract user.zip file
      ansible.builtin.unarchive:
        src: /tmp/user.zip
        dest: /app
    
    