- name : this playbook is for installong nginx
  hosts: web
  become: yes

  tasks:
    - name: insatallling nginx
      ansible.builtin.yum:
        name: nginx
        state: installed
    
    - name: starting and enabling nginx
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes
 
    - name: remove the html folder
      ansible.builtin.file:
        path: /usr/share/nginx/html/
        state: absent
    
    - name: creating the nginx folder
      ansible.builtin.file:
        path: /usr/share/nginx/html
        state: directory

    - name: downloading the web.zip file
      ansible.builtin.get_url:
       url: https://roboshop-builds.s3.amazonaws.com/web.zip
       dest: /tmp
    
    - name: extract the web.zip in /app folder
      ansible.builtin.unarchive:
        src: /tmp/web.zip
        dest: /app

        
    